# Generated by Django 2.2.1 on 2020-03-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titlte',
            new_name='title',
        ),
    ]
