# Generated by Django 2.2.1 on 2020-03-27 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200326_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
