# Generated by Django 2.2.1 on 2020-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, upload_to='post_image'),
        ),
    ]
