# Generated by Django 2.2.1 on 2020-03-18 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200318_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted_date',
        ),
    ]
