# Generated by Django 2.2.1 on 2020-03-18 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200318_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 18)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=datetime.datetime(2020, 3, 18, 16, 3, 35, 12762)),
        ),
    ]
