# Generated by Django 2.2.1 on 2020-03-18 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200318_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=datetime.datetime(2020, 3, 18, 16, 10, 45, 443984)),
        ),
    ]
