# Generated by Django 2.2.1 on 2020-03-18 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200318_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=datetime.datetime(2020, 3, 18, 19, 37, 47, 348259)),
        ),
    ]
