# Generated by Django 2.2.1 on 2020-03-18 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200318_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='default_.jpg', upload_to='post_image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=datetime.datetime(2020, 3, 18, 23, 1, 58, 161507)),
        ),
    ]
