# Generated by Django 2.2.1 on 2020-03-18 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20200318_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
