# Generated by Django 2.2.1 on 2020-03-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
