# Generated by Django 2.2.1 on 2020-03-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
