# Generated by Django 2.2.1 on 2020-03-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
