# Generated by Django 2.2.1 on 2020-03-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_image',
            new_name='image',
        ),
    ]
