# Generated by Django 2.2.1 on 2020-03-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200324_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='cover_default.jpg', upload_to='cover_pics'),
        ),
    ]
